CLASSIFIER

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [61]:
breast_cancer = load_breast_cancer()

In [72]:
breast_cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [73]:
breast_cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [74]:
breast_cancer = load_breast_cancer(as_frame=True)
breast_cancer.target.name

'target'

In [76]:
breast_cancer

{'data':      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 0          17.99         10.38          122.80     1001.0          0.11840
 1          20.57         17.77          132.90     1326.0          0.08474
 2          19.69         21.25          130.00     1203.0          0.10960
 3          11.42         20.38           77.58      386.1          0.14250
 4          20.29         14.34          135.10     1297.0          0.10030
 ..           ...           ...             ...        ...              ...
 564        21.56         22.39          142.00     1479.0          0.11100
 565        20.13         28.25          131.20     1261.0          0.09780
 566        16.60         28.08          108.30      858.1          0.08455
 567        20.60         29.33          140.10     1265.0          0.11780
 568         7.76         24.54           47.92      181.0          0.05263

      mean compactness  mean concavity  mean concave points  mean symmetry  \
 0             0.27760         0.30010              0.14710         0.2419
 1             0.07864         0.08690              0.07017         0.1812
 2             0.15990         0.19740              0.12790         0.2069
 3             0.28390         0.24140              0.10520         0.2597
 4             0.13280         0.19800              0.10430         0.1809
 ..                ...             ...                  ...            ...
 564           0.11590         0.24390              0.13890         0.1726
 565           0.10340         0.14400              0.09791         0.1752
 566           0.10230         0.09251              0.05302         0.1590
 567           0.27700         0.35140              0.15200         0.2397
 568           0.04362         0.00000              0.00000         0.1587

      mean fractal dimension  ...  worst radius  worst texture  \
 0                   0.07871  ...        25.380          17.33
 1                   0.05667  ...        24.990          23.41
 2                   0.05999  ...        23.570          25.53
 3                   0.09744  ...        14.910          26.50
 4                   0.05883  ...        22.540          16.67
 ..                      ...  ...           ...            ...
 564                 0.05623  ...        25.450          26.40
 565                 0.05533  ...        23.690          38.25
 566                 0.05648  ...        18.980          34.12
 567                 0.07016  ...        25.740          39.42
 568                 0.05884  ...         9.456          30.37

      worst perimeter  worst area  worst smoothness  worst compactness  \
 0             184.60      2019.0           0.16220            0.66560
 1             158.80      1956.0           0.12380            0.18660
 2             152.50      1709.0           0.14440            0.42450
 3              98.87       567.7           0.20980            0.86630
 4             152.20      1575.0           0.13740            0.20500
 ..               ...         ...               ...                ...
 564           166.10      2027.0           0.14100            0.21130
 565           155.00      1731.0           0.11660            0.19220
 566           126.70      1124.0           0.11390            0.30940
 567           184.60      1821.0           0.16500            0.86810
 568            59.16       268.6           0.08996            0.06444

      worst concavity  worst concave points  worst symmetry  \
 0             0.7119                0.2654          0.4601
 1             0.2416                0.1860          0.2750
 2             0.4504                0.2430          0.3613
 3             0.6869                0.2575          0.6638
 4             0.4000                0.1625          0.2364
 ..               ...                   ...             ...
 564           0.4107                0.2216          0.2060
 565           0.3215                0.1628          0.2572
 566           0.3403                0.1418          0.2218
 567           0.9387                0.2650          0.4087
 568           0.0000                0.0000          0.2871

      worst fractal dimension
 0                    0.11890
 1                    0.08902
 2                    0.08758
 3                    0.17300
 4                    0.07678
 ..                       ...
 564                  0.07115
 565                  0.06637
 566                  0.07820
 567                  0.12400
 568                  0.07039

 [569 rows x 30 columns],
 'target': 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 564    0
 565    0
 566    0
 567    0
 568    1
 Name: target, Length: 569, dtype: int64,
 'frame':      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 0          17.99         10.38          122.80     1001.0          0.11840
 1          20.57         17.77          132.90     1326.0          0.08474
 2          19.69         21.25          130.00     1203.0          0.10960
 3          11.42         20.38           77.58      386.1          0.14250
 4          20.29         14.34          135.10     1297.0          0.10030
 ..           ...           ...             ...        ...              ...
 564        21.56         22.39          142.00     1479.0          0.11100
 565        20.13         28.25          131.20     1261.0          0.09780
 566        16.60         28.08          108.30      858.1          0.08455
 567        20.60         29.33          140.10     1265.0          0.11780
 568         7.76         24.54           47.92      181.0          0.05263

      mean compactness  mean concavity  mean concave points  mean symmetry  \
 0             0.27760         0.30010              0.14710         0.2419
 1             0.07864         0.08690              0.07017         0.1812
 2             0.15990         0.19740              0.12790         0.2069
 3             0.28390         0.24140              0.10520         0.2597
 4             0.13280         0.19800              0.10430         0.1809
 ..                ...             ...                  ...            ...
 564           0.11590         0.24390              0.13890         0.1726
 565           0.10340         0.14400              0.09791         0.1752
 566           0.10230         0.09251              0.05302         0.1590
 567           0.27700         0.35140              0.15200         0.2397
 568           0.04362         0.00000              0.00000         0.1587

      mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
 0                   0.07871  ...          17.33           184.60      2019.0
 1                   0.05667  ...          23.41           158.80      1956.0
 2                   0.05999  ...          25.53           152.50      1709.0
 3                   0.09744  ...          26.50            98.87       567.7
 4                   0.05883  ...          16.67           152.20      1575.0
 ..                      ...  ...            ...              ...         ...
 564                 0.05623  ...          26.40           166.10      2027.0
 565                 0.05533  ...          38.25           155.00      1731.0
 566                 0.05648  ...          34.12           126.70      1124.0
 567                 0.07016  ...          39.42           184.60      1821.0
 568                 0.05884  ...          30.37            59.16       268.6

      worst smoothness  worst compactness  worst concavity  \
 0             0.16220            0.66560           0.7119
 1             0.12380            0.18660           0.2416
 2             0.14440            0.42450           0.4504
 3             0.20980            0.86630           0.6869
 4             0.13740            0.20500           0.4000
 ..                ...                ...              ...
 564           0.14100            0.21130           0.4107
 565           0.11660            0.19220           0.3215
 566           0.11390            0.30940           0.3403
 567           0.16500            0.86810           0.9387
 568           0.08996            0.06444           0.0000

      worst concave points  worst symmetry  worst fractal dimension  target
 0                  0.2654          0.4601                  0.11890       0
 1                  0.1860          0.2750                  0.08902       0
 2                  0.2430          0.3613                  0.08758       0
 3                  0.2575          0.6638                  0.17300       0
 4                  0.1625          0.2364                  0.07678       0
 ..                    ...             ...                      ...     ...
 564                0.2216          0.2060                  0.07115       0
 565                0.1628          0.2572                  0.06637       0
 566                0.1418          0.2218                  0.07820       0
 567                0.2650          0.4087                  0.12400       0
 568                0.0000          0.2871                  0.07039       1

 [569 rows x 31 columns],
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [80]:
breast_cancer.data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
X, y = breast_cancer.data, breast_cancer.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42)

In [6]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [7]:
y_pred = dt.predict(X_test)

In [8]:
accuracy_score(y_test, y_pred)

0.9473684210526315

In [31]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [32]:
y_pred = rf.predict(X_test)

In [33]:
accuracy_score(y_test, y_pred)

0.9649122807017544

In [34]:
ada = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),random_state=42)
ada.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   random_state=42)

In [35]:
y_pred = ada.predict(X_test)

In [36]:
accuracy_score(y_test, y_pred)

0.9649122807017544

Regression

In [45]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor

In [46]:
diabetes = load_diabetes()

In [77]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [78]:
diabetes = load_diabetes(as_frame=True)
diabetes.target.name

'target'

In [79]:
diabetes

{'data':           age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5        s6
 0   -0.002592  0.019907 -0.017646
 1   -0.039493 -0.068332 -0.092204
 2   -0.002592  0.002861 -0.025930
 3    0.034309  0.022688 -0.009362
 4   -0.002592 -0.031988 -0.046641
 ..        ...       ...       ...
 437 -0.002592  0.031193  0.007207
 438  0.034309 -0.018114  0.044485
 439 -0.011080 -0.046883  0.015491
 440  0.026560  0.044529 -0.025930
 441 -0.039493 -0.004222  0.003064

 [442 rows x 10 columns],
 'target': 0      151.0
 1       75.0
 2      141.0
 3      206.0
 4      135.0
        ...
 437    178.0
 438    104.0
 439    132.0
 440    220.0
 441     57.0
 Name: target, Length: 442, dtype: float64,
 'frame':           age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5        s6  target
 0   -0.002592  0.019907 -0.017646   151.0
 1   -0.039493 -0.068332 -0.092204    75.0
 2   -0.002592  0.002861 -0.025930   141.0
 3    0.034309  0.022688 -0.009362   206.0
 4   -0.002592 -0.031988 -0.046641   135.0
 ..        ...       ...       ...     ...
 437 -0.002592  0.031193  0.007207   178.0
 438  0.034309 -0.018114  0.044485   104.0
 439 -0.011080 -0.046883  0.015491   132.0
 440  0.026560  0.044529 -0.025930   220.0
 441 -0.039493 -0.004222  0.003064    57.0

 [442 rows x 11 columns],
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [81]:
diabetes.frame.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [47]:
X,y = diabetes.data, diabetes.target

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42)

In [49]:
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [50]:
y_pred = dt.predict(X_test)

In [51]:
r2_score(y_test, y_pred)

0.060653981041140725

In [52]:
dpt = DecisionTreeRegressor(random_state=42, ccp_alpha=0.015)
dpt.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.015, random_state=42)

In [53]:
y_pred = dpt.predict(X_test)

In [54]:
r2_score(y_test, y_pred)

0.059900103558396145

In [55]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [56]:
y_pred = rf.predict(X_test)

In [57]:
r2_score(y_test, y_pred)

0.4428225673999313

In [58]:
ada = AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=1),random_state=42)
ada.fit(X_train, y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=1), random_state=42)

In [59]:
y_pred = ada.predict(X_test)

In [60]:
r2_score(y_test, y_pred)

0.3834798906194006